Kennighan/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('louis/', include('website.urls')),
]

website/urls.py
from django.urls import path

from . import views

app_name = 'website'         #permettra de différencier l'application utilisé lorsqu'on utilise {% url inside:detail %}
                            #dans le cas ou on aurais une autre application avec une vue nommé 'detail'
urlpatterns = [
    # / -> redirect to homepage
    path ('', views.home, name = 'home'),
    path ('hidden/', views.hidden, name='hidden')
    # /inside/5/
    #path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    ]

website/models.py
from django.db import models

# Create your models here.

website/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'website/home.html')

def hidden(request):
    return render(request, 'website/hidden.html')

website/templates/website/base.html
<!DOCTYPE html>
<html>
	<body>
		<head>
	
	    <meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <meta name="description" content="">
	    <meta name="author" content="">
	
	    <title>Title</title>
	
		{% load static %}
	    <!-- Bootstrap Core CSS -->
	    <link rel="stylesheet" type="text/css" href="{% static 'website/bootstrap/bootstrap.min.css' %}" />
	    <link rel="stylesheet" type="text/css" href="{% static 'website/css/style.css' %}" />
		</head>
		
		<div class="container">
	    	<div class="row">
			    {% block content %} {% endblock %}
			</div>
		</div>
		
		
		
		<!-- jQuery -->
	    <script src="{% static 'website/bootstrap/jquery.min.js' %}"></script>
	    
	    
	    <!-- Bootstrap Core JavaScript -->
	    <script src="{% static 'website/bootstrap/bootstrap.min.js' %}"></script>
	</body>
</html>

website/templates/website/hidden.html
{% extends 'website/base.html' %}
{% block content %}
		<div class="col-12">
		<div class="row"><h4>Kernighan <a href="{% url 'website:home' %}">&</a> Ritchie les biatchs surs</h4></div>
		<div class="row" style="margin:20px"></div>
		<div class="row">
			<div class="col-12 offset-md-4 col-md-4" id="imgZone">
				{% load static %}
				<img class="imgOff"src="{% static 'website/img/Im1.jpg' %}" alt="Jul Jul Jul" style="height:500px; width:auto"/>
				<img class="imgOn"src="{% static 'website/img/Im2-pS.jpg' %}" alt="Jul Jul Jul" style="height:500px; width:auto"/>
			</div>
		</div>
		</div>
		
			
		<style>
			#imgZone{
				position:relative;
  				height:281px;
				width:450px;
				margin:0 auto;
			}
			#imgZone img{
				position:absolute;
				left:0;
				-webkit-transition: opacity 1s ease-in-out;
				-moz-transition: opacity 1s ease-in-out;
				-o-transition: opacity 1s ease-in-out;
				transition: opacity 1s ease-in-out;
			}
			#imgZone img.imgOn:hover{
				opacity:0;
			}
			
			/* #imgOff{
				display:none;
			}
			#imgOff:hover{
				display:inline-block;
			} */
			.redB
			{
				border: 1px solid red;
			}
			.blueB
			{
				border: 1px solid blue;
			}
			.greenB
			{
				border: 1px solid green;
			}
			.orangeB
			{
				border: 1px solid orange;
			}
		</style>
{% endblock %}

website/templates/website/home.html
{% extends 'website/base.html' %}
{% block content %}
		<h4>Kernighan <a href="{% url 'website:hidden' %}">&</a> Ritchie</h4>
{% endblock %}